//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isip_523_Sidorov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wherehorse
    {
        public int DetailID { get; set; }
        public int Amount { get; set; }
        public int PlayerID { get; set; }
        public int ID { get; set; }
    
        public virtual Details Details { get; set; }
        public virtual Player Player { get; set; }
    }
}
