//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsoluteCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionSeat
    {
        public int SessionSeatID { get; set; }
        public int SeatID { get; set; }
        public int SessionID { get; set; }
        public bool Taken { get; set; }
    
        public virtual Seats Seats { get; set; }
        public virtual Session Session { get; set; }
    }
}
