//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidorov_Isip523
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Cart
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public int Amount { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Products Products { get; set; }

    }
}
