//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidorov_Isip523
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Ordering_Prod = new HashSet<Ordering_Prod>();
        }
    
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int CartID { get; set; }
        public int PvzID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual PVZ PVZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordering_Prod> Ordering_Prod { get; set; }
    }
}
